### ISSUE TITLE
Allow version filtering / exclusions

### ISSUE THREAD

**Issue by DanySK** [jmfayard/refreshVersions#192]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I'm proposed upgrades that I definitely cannot apply.
For instance, some libraries maintain different JVM compatibility on different versions.
Take FST for instance: version 2.x is JDK-8 compatible, version 3.x is JDK-14 compatible.
I'd like a way to tell refreshVersions to keep me on the latest 2.x version

**Describe the solution you'd like**

Very open to discussion.
I believe this project has a lot of space for configurability: version groups (see #186) and filtering are just examples.
I thus suggest switching to a yaml/toml (or both, e.g. via Konf) configuration file, containing both custom artifact version key rules and additional customizations.

something like:
```yaml
custom_key_rules:
  - mydescriptor.txt
  - myothercustomkeyrules.txt
custom_ranges:
# I'd inherit https://docs.gradle.org/current/userguide/single_versions.html, e.g.:
  - version.de.ruedigermoeller..fst: [, 3.)
# or:
  - version.de.ruedigermoeller..fst: '2.+'

```

**Describe alternatives you've considered**

Uhmm... Kotlin customization to settings.gradle.kts maybe is another way.
