### ISSUE TITLE
Caveat: refreshVersions might show available updates in versions catalog for dependencies you don't actually use

### ISSUE THREAD

**Issue by jmfayard** [jmfayard/refreshVersions#571]
The next version of refreshVersions will support Gradle Versions Catalog.

## Caveat

The task `./gradlew refreshVersions` will show available updates inside `gradle/libs.versions.toml`

```toml
 [versions]
 okhttp3 = "3.5.0"
### available = "3.6.0"
### available = "3.7.0"

 [libraries]
 okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3" }
```

The issue is: what happens to your build if you upgrade the version in that file?

Well actually... nothing if you don't use `implementation(libs.okhttp)`  everywhere in your build.

If you have hardcoded it with `implementation("com.squareup.okhttp3:okhttp:4.10.0")`, then nothing will happen.

## Workaround

If you run the task `./gradlew refreshVersionsMigrate`, your build will be updated to use the dependency notations

If the versions in Gradle (4.10.0) and the `gradle/libs.versions.toml` file are different, refreshVersions will detect that and mark the `okhttp` property as being unused (`## unused`) to avoid confusing you.

On the other hand, if it's the same version, you will see the updates and only get the unused comment in the next run.
